### ISSUE TITLE
Please Release Version: 2.7.2

### ISSUE THREAD

**Issue by ngcly** [webjars/layui#17]

**Comment by jamesward** [comment]
I'm getting an error:

> unable to resolve host address ‘res.layui.com’

Not sure what happened to their site.

**Comment by ngcly** [comment]
Yes, their site has gone offline and the new home page has been moved to gitee. [https://layui.gitee.io/v2/](url)

**Comment by jamesward** [comment]
Working on this for #18 - let me know if you also need this version.
